# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170904_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
