# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_song_pinyintype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='productionPerformance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Song'),
        ),
    ]
