# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171203_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taiwanese', models.CharField(blank=True, max_length=10)),
                ('phonetic', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
